org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# The Minecraft version must agree with the Forge version to get a valid artifact


minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.22
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mixin_version=0.8.5
lombok_version=1.18.+
jei_version=15.2.0.27

mod_id=academycraft
mod_name=AcademyCraft
mod_license=GNU AGPL 3.0
mod_version=1.0.1
mod_version_tag=alpha1
mod_group_id=committee.nova.mods
mod_authors=cnlimiter
mod_description=



