modLoader = "javafml"
loaderVersion = "${fmljava_range}"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = ""
displayURL = ""
logoFile = "logo.png"
authors = "${mod_authors}"

description='''${mod_description}'''

[[mixins]]
config = "mixins.${mod_id}.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_range}"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_range}"
ordering = "NONE"
side = "BOTH"
